services:
  medpho_db:
    image: postgres:latest
    container_name: medpho_db
    env_file: .env
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql 
    networks:
      - medpho_net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- backend_app ---
  backend_app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: medpho_backend
    env_file: ./backend/.env
    ports:
      - "9001:8000"  # <-- KEPT FOR TESTING
    restart: unless-stopped 
    networks:
      - medpho_net
    depends_on:
      medpho_db:
        condition: service_healthy

  metabase:
    image: metabase/metabase:latest
    container_name: medpho_metabase
    env_file: .env
    environment:
      MB_DB_TYPE: postgres
      MB_DB_HOST: medpho_db
      MB_DB_PORT: ${POSTGRES_PORT}
      MB_DB_DBNAME: ${POSTGRES_DB}
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
    ports:
      - "${METABASE_PORT}:3000"
    volumes:
      - metabase_data:/metabase-data
    restart: unless-stopped
    networks:
      - medpho_net
    depends_on:
      medpho_db:
        condition: service_healthy

  # 4. --- NEW frontend_app SERVICE ---
  frontend_app:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: medpho_frontend
    ports:
      - "80:80"
    networks:
      - medpho_net
    restart: unless-stopped
    depends_on:
      - backend_app # Waits for the backend to be ready

volumes:
  metabase_data:
  postgres_data:

networks:
  medpho_net:
    driver: bridge